# Generated by Django 4.0.1 on 2022-03-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.team'),
        ),
    ]
